### ISSUE TITLE
AttributeError: 'Transaction' object has no attribute 'UserClass'

### ISSUE THREAD

**Issue by FelixJacobi** [HenriWahl/dhcpy6d#47]
~~~
Okt 01 02:01:32 iserv.stsbl.de dhcpy6d[6264]: Uncolonifyable address:
Okt 01 02:01:32 iserv.stsbl.de dhcpy6d[6264]: Uncolonifyable address:
Okt 01 02:01:32 iserv.stsbl.de dhcpy6d[6264]: Uncolonifyable address:
Okt 01 02:01:32 iserv.stsbl.de dhcpy6d[6264]: Traceback (most recent call last):
Okt 01 02:01:32 iserv.stsbl.de dhcpy6d[6264]:   File "/usr/lib/python3/dist-packages/dhcpy6d/client/__init__.py", line 231, in build
Okt 01 02:01:32 iserv.stsbl.de dhcpy6d[6264]:     from_config(client=self, client_config=client_config, transaction=transaction)
Okt 01 02:01:32 iserv.stsbl.de dhcpy6d[6264]:   File "/usr/lib/python3/dist-packages/dhcpy6d/client/from_config.py", line 99, in from_config
Okt 01 02:01:32 iserv.stsbl.de dhcpy6d[6264]:     transaction.UserClass == user_class):
Okt 01 02:01:32 iserv.stsbl.de dhcpy6d[6264]: AttributeError: 'Transaction' object has no attribute 'UserClass'
Okt 01 02:01:32 iserv.stsbl.de dhcpy6d[6264]: 2021-10-01 02:01:32,173 dhcpy6d ERROR build(): 'Transaction' object has no attribute 'UserClass'
~~~

Just found log after upgrading another production system to Bullseye. Seems to be related to boot files. As far as I can see, the `UserClass` was renamed to `user_class` is Transaction which is the only problem here.

**Comment by HenriWahl** [comment]
Please check latest release from https://github.com/HenriWahl/dhcpy6d/releases/tag/latest

**Comment by xtaran** [comment]
> Just found log after upgrading another production system to Bullseye. Seems to be related to boot files. As far as I can see, the `UserClass` was renamed to `user_class` is Transaction which is the only problem here.

So this is an issue in Debian's official 1.0.3-1 package in Bullseye as well? Or did you use dhcpy6d of git or upstream release tar balls?

**Comment by HenriWahl** [comment]
Yes, sad to say but this error exists in 1.0.3 Debian package too:

https://salsa.debian.org/search?utf8=%E2%9C%93&search=userclass&group_id=2&project_id=52793&scope=&search_code=true&snippets=false&repository_ref=master&nav_source=navbar

**Comment by xtaran** [comment]
> Yes, sad to say but this error exists in 1.0.3 Debian package too:
> 
> https://salsa.debian.org/search?utf8=%E2%9C%93&search=userclass&group_id=2&project_id=52793&scope=&search_code=true&snippets=false&repository_ref=master&nav_source=navbar

This seems to look in the current 1.0.5-1 package from Debian Unstable/Testing. But, yes, 1.0.3-1 has that as well: 
https://salsa.debian.org/search?utf8=%E2%9C%93&search=userclass&group_id=2&project_id=52793&scope=&search_code=true&snippets=false&repository_ref=debian%2F1.0.3-1&nav_source=navbar

So I should probably prepare a stable update in addition to preparing an upload of 1.0.7-1.

**Comment by xtaran** [comment]
@HenriWahl: Can you give me a summary of the impact of this issue, i.e. what breakage can be caused by this, what feature doesn't work? I don't see such traces in my logs, at least not in those logs from this month.

**Comment by xtaran** [comment]
Tracked in Debian as https://bugs.debian.org/995484

**Comment by HenriWahl** [comment]
@xtaran this bug leads to PXE boot malfunction. Not the main feature but unpleasant anyway.

**Comment by xtaran** [comment]
> @xtaran this bug leads to PXE boot malfunction. Not the main feature but unpleasant anyway.

Ah, thanks! I was already wondering what "boot" in the original bug report refers, too. Thanks for the clarification!

**Comment by FelixJacobi** [comment]
> Please check latest release from https://github.com/HenriWahl/dhcpy6d/releases/tag/latest

Works fine for me. Thanks.
